In [1]:
import numpy as np

In [2]:
results=[]
for i in range(5):
    lognormal_params = np.loadtxt('/gpfs7kw/linkhome/rech/genmfd01/ulm75uc/CosMomentum/Data/result_test/shift_dep_test%i.txt' %i, skiprows=1, delimiter=',')
    shifts=lognormal_params[:,...,-1]
    shifts_fid=shifts[0]
    shifts_nofid=shifts[1:]
    diff=np.stack(np.split(shifts_nofid, 5))
    frac_diff=abs((diff[:, 0]-diff[:, 1])/shifts_fid)
    results.append(frac_diff)

In [3]:
results

[array([0.01944655, 0.00629004, 0.06336393, 2.13612183, 0.33692504]),
 array([0.01857852, 0.00650773, 0.04482991, 1.91313732, 0.2446402 ]),
 array([0.01785209, 0.0066662 , 0.02799985, 1.71724848, 0.18308648]),
 array([0.01660912, 0.00658103, 0.01016876, 1.51174971, 0.12547051]),
 array([0.01286324, 0.00559975, 0.01554037, 1.19374055, 0.03742106])]