In [1]:
import numpy as np

In [5]:
w0=np.linspace(-0.33,-2,10)
s8=np.linspace(0.3,1.3,10)
om=np.linspace(0.1,0.9,10)

In [8]:
om

array([0.1       , 0.18888889, 0.27777778, 0.36666667, 0.45555556,
       0.54444444, 0.63333333, 0.72222222, 0.81111111, 0.9       ])

In [9]:
s8

array([0.3       , 0.41111111, 0.52222222, 0.63333333, 0.74444444,
       0.85555556, 0.96666667, 1.07777778, 1.18888889, 1.3       ])

In [10]:
w0

array([-0.33      , -0.51555556, -0.70111111, -0.88666667, -1.07222222,
       -1.25777778, -1.44333333, -1.62888889, -1.81444444, -2.        ])